CREATE TABLE USER_INFO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);


INSERT INTO USER_INFO (ID, EMAIL, FULL_NAME, PASSWORD) VALUES (1212, 'd@g','deepak','d');